//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebADS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyIphonesvEntities : DbContext
    {
        public MyIphonesvEntities()
            : base("name=MyIphonesvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<Facturacion> Facturacion { get; set; }
        public virtual DbSet<HistorialCambios> HistorialCambios { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Recibos> Recibos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vista_Admin> Vista_Admin { get; set; }
        public virtual DbSet<Vista_Empleados> Vista_Empleados { get; set; }
        public virtual DbSet<Vista_Usuarios> Vista_Usuarios { get; set; }
    
        public virtual int GenerarRecibo(Nullable<int> clienteID, Nullable<int> pedidoID)
        {
            var clienteIDParameter = clienteID.HasValue ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(int));
    
            var pedidoIDParameter = pedidoID.HasValue ?
                new ObjectParameter("PedidoID", pedidoID) :
                new ObjectParameter("PedidoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerarRecibo", clienteIDParameter, pedidoIDParameter);
        }
    
        public virtual ObjectResult<ReporteProductosMasVendido_Result> ReporteProductosMasVendido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReporteProductosMasVendido_Result>("ReporteProductosMasVendido");
        }
    }
}
