//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebADS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int FacturaID { get; set; }
        public int PedidoID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public decimal MontoTotal { get; set; }
        public int ClienteID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Pedidos Pedidos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
