//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebADS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_CarritoCompras
    {
        public int CarritoID { get; set; }
        public string UsuarioNombre { get; set; }
        public string ProductoNombre { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string ImagenProducto { get; set; }
    }
}
