//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebADS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Admin
    {
        public int Producto_ID { get; set; }
        public string Producto_Nombre { get; set; }
        public string Producto_Descripcion { get; set; }
        public decimal Producto_Precio { get; set; }
        public int Producto_Stock { get; set; }
        public int Cliente_ID { get; set; }
        public string Cliente_Nombre { get; set; }
        public string Cliente_Correo { get; set; }
        public int Pedido_ID { get; set; }
        public Nullable<System.DateTime> Pedido_Fecha { get; set; }
        public decimal Pedido_Total { get; set; }
        public string Pedido_Estado { get; set; }
    }
}
